### ISSUE TITLE
Document the rest

### ISSUE THREAD

**Issue by Jambls** [daft-engineers/vocoder#102]
- Document the rest to Doxy compatible javadoc standard.
- Fix filter.hh not having th  timeout and having the output pipe malformed on the constructor.
- Document the pipe extra carefully, potentially with a usage example.

Filter.hh and the [doxy manual](https://www.doxygen.nl/manual/docblocks.html) may be useful.

**Comment by MarkAHarley** [comment]
Add something to the readme about restore.
