### ISSUE TITLE
Amplifier module

### ISSUE THREAD

**Issue by MarkAHarley** [daft-engineers/vocoder#11]
As a daft engineer, I want to be able to adjust the level of signals. This will be useful for accentuating the human voice components and also controlling overall levels at the output.

Success Criteria:
- UML Class Diagram
- Decide on units (dB / linear)
- Scale input signal by whatever factor
- Output new signal

**Comment by bear-in-the-air** [comment]
for standup:

Settling on a name for this class? There's a header called amp and this ticket is called level control. 

talk about units

**Comment by bear-in-the-air** [comment]
From standup:

This is the amplifer, the level meter is going to be separate. 
unit: linear is fine, as it's theoretically easier and as long as it matches the level meter.
