### ISSUE TITLE
Mixer Stage

### ISSUE THREAD

**Issue by MarkAHarley** [daft-engineers/vocoder#12]
As a daft engineer, I want to create a mixer to combine multiple signals so that all the filter outputs can be combined.

Sucess Criteria:
- UML Class diagram
- Logic for combining signals

**Comment by MHCooke** [comment]
This is the class interface I'll be using

```cpp
template <std::size_t num_banks> class Mixer {
private:
    std::array<Pipe<Audio>, num_banks> input_pipes;
    Pipe<Audio> output_pipe;
    
public:
    Mixer (std::array<Pipe<Audio>, num_banks> input_pipes, Pipe<Audio> output_pipe);
    void run();
};
```
