### ISSUE TITLE
Add command line arguments

### ISSUE THREAD

**Issue by MarkAHarley** [daft-engineers/vocoder#125]
Some variables should be defined in the command line to make them easily configurable by the user. These include:

- ALSA input and output handles
- Microphone gain
- Number of filters

All of these should have default values.
Check if c++ has a modern version of command line args other than main(argv[])....

**Comment by MHCooke** [comment]
I wonder if a whole config file would be a better idea. We have quite a lot of magic numbers and it would be good to have them in one place where they can be edited without recompilation.

**Comment by MHCooke** [comment]
Magic numbers:
- Input device name
- Output device name
- number of filters
- number of samples in rms history
- thread timeout
- vocoder filter frequency range
