### ISSUE TITLE
Data flow

### ISSUE THREAD

**Issue by MarkAHarley** [daft-engineers/vocoder#24]
As a developer, I want to be able to view the software data flow so that I can implement modules

- Create an overarching data flow diagram for the system (sequence diagram)

**Comment by MHCooke** [comment]
![Image](https://user-images.githubusercontent.com/10051310/220790624-48ad3c57-34fe-4f8b-b89b-a98e7c718f88.png)

Example

**Comment by MHCooke** [comment]
Latex TikZ-UML Source

[Vocoder Sequence Diagram.zip](https://github.com/daft-engineers/vocoder/files/10809240/Vocoder.Sequence.Diagram.zip)
