### ISSUE TITLE
Testing framework

### ISSUE THREAD

**Issue by MHCooke** [daft-engineers/vocoder#25]
As a developer, I want to unit test my code so that I can be more confident that it will not regress.

- Choose a testing framework

**Comment by Jambls** [comment]
I feel that googltest is probably the best option to start with, it seems to top lists most often. I don't know if it lets you test "embedded" stuff easily, but I don't think what we're doing is actually truly embedded.

@MHCooke @MarkAHarley @bear-in-the-air what do yous think?

**Comment by MarkAHarley** [comment]
Google Test seems pretty intuitive, would be happy to go for that.

**Comment by Jambls** [comment]
Fine by me.
