### ISSUE TITLE
Linting standard

### ISSUE THREAD

**Issue by MHCooke** [daft-engineers/vocoder#27]
As a developer, I want to keep all the code looking consistent so that I can read other developers code more easily.

- Choose a linting standard (one with the curly brackets generally on the same line as the thing they're attached to)

**Comment by MHCooke** [comment]
LLVM is decent but I have two issues with it, which we might be able to fix:

- preference to omit braces around single line control flow

- and whatever this is:
```cpp
Cowboy::Cowboy()
    : Age(45), GunCount(2) {
  std::cout << "I am alive!" << std::endl;
}
```

**Comment by MarkAHarley** [comment]
GNU is my personal favourite but if we're going for one in the in-line group I would go for LLVM.

**Comment by Jambls** [comment]
I'm happy with LLVM.
