### ISSUE TITLE
alsa driver

### ISSUE THREAD

**Issue by MarkAHarley** [daft-engineers/vocoder#29]
As a vodcoder developer, I want to know what way we will interact with the driver so that I can start development

- Research the Alsa driver and options for working with it
- Choose between using a cpp abstraction on top of it or using the c driver as it is

port audio seems seems to be a high level cpp option that supports callbacks

**Comment by Jambls** [comment]
I can't find any information on using alsa with callbacks for audio input.
On the other hand, JACK seems to do [this by default.](https://jackaudio.org/faq/making_a_jack_app.html)
However, it's a c library. Someone has made an [abstraction layer for cpp](https://github.com/x37v/jackcpp) though.

**Comment by Jambls** [comment]
Jack actually has a cpp version in active development. The docs are poorer, but it should be the easiest to integrate. It seems like the best option at the moment.
