### ISSUE TITLE
Audio in driver

### ISSUE THREAD

**Issue by MHCooke** [daft-engineers/vocoder#30]
As a vocoder developer, I want to have audio packets trigger events so that I can process audio in real time.

- some callback triggered by the audio api

**Comment by Jambls** [comment]
This will probably use jack as described by #29

**Comment by MHCooke** [comment]
Fixed.

**Comment by MHCooke** [comment]
Not going to use jack after speaking to Bernd, he reckons interfacing with ALSA directly is simple enough. I will investigate writing a small self contained class which listens to also continuously and triggers a call back function periodically.

**Comment by MHCooke** [comment]
Will implement this in a new repository.

**Comment by MHCooke** [comment]
Will not implement this in a new repo due to effort required to correctly wrap something as a library. It is not worth writing a 150 line CMakeLists file for a 100 line C++ file. Solution is implemented in #61
