### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by Jambls** [daft-engineers/vocoder#40]
As a user looking to build the project, I need to be able to source the dependencies so that I can build it. 

- Investigate git submodules/ apt/ whatever
- Investigate copyright for dependencies, berndt's filter in particular. 
- must be automated

**Comment by MHCooke** [comment]
Multiple answers in this thread on SO suggest [Conan ](https://github.com/conan-io/conan) is the best solution. Will investigate further

**Comment by MHCooke** [comment]
Conan has the IIR library: https://conan.io/center/iir1?tab=overview&os=

**Comment by MHCooke** [comment]
Conan has a python 3.6+ dependency, but I'm pretty sure we already need python for gtest (cmake searches for it certainly)
