### ISSUE TITLE
Update alsa callback generator

### ISSUE THREAD

**Issue by MHCooke** [daft-engineers/vocoder#64]
As a daft engineer I want the class to safely stop itself in the event it is misused and `stop()` is not called.

Success criteria:
- ALSA callback generator class should implement a destructor that calls stop if the listener is still running.

**Comment by MarkAHarley** [comment]
If we change to using waits with timeouts this doesn't seem worth doing.

**Comment by MHCooke** [comment]
We now need to get rid of destructors.
